# Generated by Django 5.0.6 on 2024-05-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название задачи', max_length=100, verbose_name='Название задачи')),
                ('description', models.TextField(help_text='Введите описание задачи', verbose_name='Описание задачи')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнена ли задача')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
